// src/lib/fields-of-study.ts
export const FIELDS_OF_STUDY = [
  "Actuariat",
  "Agronomie",
  "Architecture",
  "Arts et design",
  "Biologie",
  "Chimie",
  "Comptabilité",
  "Droit",
  "Économie",
  "Électronique",
  "Finance",
  "Génie civil",
  "Génie électrique",
  "Génie logiciel",
  "Génie mécanique",
  "Géographie",
  "Gestion",
  "Histoire",
  "Informatique",
  "Journalisme et communication",
  "Langues étrangères appliquées",
  "Lettres modernes",
  "Marketing",
  "Mathématiques",
  "Médecine",
  "Pharmacie",
  "Physique",
  "Psychologie",
  "Réseaux et télécommunications",
  "Ressources humaines",
  "Sciences de l'éducation",
  "Sciences de l'environnement",
  "Sciences infirmières",
  "Sciences politiques",
  "Sociologie",
  "Statistique",
  "Urbanisme",
].sort((a, b) => a.localeCompare(b, "fr"));
